let startBtn = document.querySelector(".startBtn"),
  easy = document.querySelector("#s1"),
  medium = document.querySelector("#s2"),
  hard = document.querySelector("#s3"),
  textIn = document.querySelector(".text-in"),
  Word1 = document.querySelectorAll(".nword")[0],
    Word2 = document.querySelectorAll(".nword")[1],
    Word3 = document.querySelectorAll(".nword")[2],
